<?php
session_start();
require_once('../lib/Util.php');
require_once('../lib/User.php');
require_once('../lib/Picture.php');
$util = new Util();
$user = new User();
$picture = new Picture();
$util->ShowErrors(1);
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<title>HappyBox :: Data Privacy Statement</title>

<!-- Bootstrap core CSS -->
<?php include 'shared/partials/css.php'; ?>
</head>

<body class="client_body">
<!-- Navigation -->
<?php include 'shared/partials/nav.php'; ?>
<!-- Page Content -->

<section class=" terms_banner">
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-center">
				<h3 class="text-white">PRIVACY POLICY</h3>
			</div>
		</div>
	</div>
</section>
<section class=" terms_sub_banner">
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-center">
				<h4 class=""> HappyBox Data Privacy Statement <br>
				<i> As of 1st October  2020</i> </h4>
			</div>
		</div>
	</div>
</section>

<!--end discover our selection-->
<section class="container section_padding_top terms_content">
	<div class="row">
		<div class="col-md-12">
			<div class="terms_li">
				<h5>1. Introduction</h5>
				<p>HappyBox ("us", "we", or "our") operates <a href="https://happybox.ke">https://happybox.ke</a> (hereinafter referred to as "Service").
					Our Privacy Policy governs your visit to <a href="https://happybox.ke">https://happybox.ke</a>, and explains how we collect, safeguard and disclose information that results from your use of our Service.
					We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions. Where there is a conflict, this statement will prevail. This privacy notice supplements the other notices and is not intended to override them. </p>
			</div>
			<div class="terms_li">
				<h5>2. Definitions</h5>
				<p><strong>SERVICE</strong> means the <a href="https://happybox.ke">https://happybox.ke</a> website operated by HappyBox.</p>
				<p><strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
				<p><strong>USAGE DATA</strong> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
				<p><strong>COOKIES</strong> are small files stored on your device (computer or mobile device).</p>
				<p><strong>DATA CONTROLLER</strong> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
				<p><strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>
				<p><strong>DATA SUBJECT</strong> is any living individual who is the subject of Personal Data.</p>
				<p><strong>THE USER</strong> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
				
			</div>
			<div class="terms_li">
				<h5>3. Information Collection and Use</h5>
				<p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
			</div>
			<div class="terms_li">
				<h5>4. Types of Data Collected</h5>
				<p>The information we collect and store about you includes but is not limited to the following: </p>
				<ol style="list-style-type: none;">
					<li>a) Personal Data<br> While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (You can update your information at any time on <a href="https://happybox.ke">https://happybox.ke</a>.). Personally identifiable information may include, but is not limited to first name and last name, e-mail address, phone number, physical address, etc.</li>
					<li>b) Preferences<br>	Your preferences for particular products, based on information provided by you or from your use of HappyBox's products.</li>					
				</ol>
			</div>
			<div class="terms_li">
				<h5>5. Cookies and Usage Data</h5>
				<p><strong>Usage Data</strong></p>
				<p>We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (<strong>"Usage Data"</strong>).</p>
				<p>This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
				<p>When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.</p>
				<p><strong>Tracking Cookies Data</strong></p>
				<p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. We also use Security Cookies for security purposes.</p>
				<p>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.</p>
				<p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
			</div>
			<div class="terms_li">
				<h5>6. Use of Data</h5>
				<p>HappyBox uses the collected data for various purposes:</p>
				<ul>
					<li>To provide and maintain our Service;</li>
					<li>To notify you about changes to our Service;</li>
					<li>To provide customer support;</li>
					<li>To gather analysis or valuable information so that we can improve our Service;</li>
					<li>To monitor the usage of our Service;</li>
					<li>To detect, prevent and address technical issues;</li>
					<li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</li>
					<li>For any other purpose with your consent.</li>
				</ul>
			</div>
			<div class="terms_li">
				<h5>7. Direct Marketing</h5>
				<p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you.</p>
				<p>You may be required to opt in before receiving marketing messages from us.</p>
				<p>You can ask us to stop sending you marketing messages at any time by logging into our website, <a href="https://happybox.ke">https://happybox.ke</a> and checking or unchecking relevant boxes to modify your preferences.</p>
			</div>
			<div class="terms_li">
				<h5>8. Retention of Data</h5>
				<p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
				<p>Anonymised information that can no longer be associated with you may be held indefinitely.</p>
				<p>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
			</div>						
			<div class="terms_li">
				<h5>9. Transfer of Data</h5>
				<p>Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
				<p>If you are located outside Kenya and choose to provide information to us, please note that we transfer the data, including Personal Data, to Kenya and process it there.</p>
				<p>HappyBox will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
			</div>
			<div class="terms_li">
				<h5>10. Disclosure of Data</h5>
				<p>Any disclosure of your information shall be in accordance with applicable law and regulations. We may disclose personal information that we collect, or you provide:</p>
				<ol style="list-style-type: none;">
					<li>a) Business Transaction<br> If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</li>
					<li>b) Other cases. We may disclose your information also:<br>	Your preferences for particular products, based on information provided by you or from your use of HappyBox's products.
						<ul>
							<li>To our subsidiaries and affiliates;</li>
							<li>To contractors, service providers, software developers, survey agencies and other third parties we use to support our business;</li>
							<li>To comply with a legal obligation;</li>
							<li>To protect against legal liability;</li>
							<li>To prevent or investigate possible wrongdoing in connection with the Service;</li>
							<li>If we believe disclosure is necessary or appropriate to protect and defend the rights, property, or safety of the Company, users of the Services, or others;</li>
							<li>With your consent in any other cases.</li>
						</ul>
					</li>					
				</ol>
			</div>
			<div class="terms_li">
				<h5>11. Spectators</h5>
				<p>HappyBox has put in place technical and operational measures to protect your information from unauthorised access, accidental loss or destruction.</p>
				<p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
			</div>
			<div class="terms_li">
				<h5>12. Service Providers</h5>
				<p>We may employ third party companies and individuals to facilitate our Service (<strong>"Service Providers"</strong>), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>
				<p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
			</div>
			<div class="terms_li">
				<h5>13. Analytics</h5>
				<p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
				<p><strong>Google Analytics</strong></p>
				<p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
				<p>You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.</p>
				<p>For more information on the privacy practices of Google, please visit the Google Privacy &amp; Terms web page: <a href="https://policies.google.com/privacy?hl=en" target="_blank">https://policies.google.com/privacy?hl=en</a></p>
			</div>
			<div class="terms_li">
				<h5>14. CI/CD tools</h5>
				<p>We may use third-party Service Providers to automate the development process of our Service.</p>
			</div>
			<div class="terms_li">
				<h5>15. Payments</h5>
				<p>We may provide paid products within Service. In that case, we use third-party services for payment processing (e.g. payment processors).</p>
				<p>We will not store or collect your payment card or MPESA details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy.</p>
			</div>
			<div class="terms_li">
				<h5>16. Links to Other Sites</h5>
				<p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
				<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
			</div>
			<div class="terms_li">
				<h5>17. Children's Privacy</h5>
				<p>Our Services are not intended for use by children under the age of 18 (<strong>"Child"</strong> or <strong>"Children"</strong>).</p>
				<p>We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.</p>
			</div>
			<div class="terms_li">
				<h5>18. Changes to This Privacy Policy</h5>
				<p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
				<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
			</div>
			<div class="terms_li">
				<h5>19. Contact Us</h5>
				<p>If you have any questions about this Privacy Policy, please contact us by phone on <a href="tel:+254112454540">+254 112 454 540</a> or by email at <a href="mailto:customerservices@happybox.ke">customerservices@happybox.ke</a>.</p>
			</div>
		</div>
	</div>
</section>
<!--end add to cart cards--> 
<!--our partners -->

<?php include 'shared/partials/partners.php';?>
<?php include 'shared/partials/footer.php';?>

<!-- Bootstrap core JavaScript -->

<?php include 'shared/partials/js.php';?>
</body>
</html>
>>>>>>> 2a0d659d090f19ad53c6a805a53c5dc2ed9cba53
